// Generated by generateColorScaleArtifact('#000', true, {
//   20: '#C6C6C6',
// }, false)

import type { EmphasisLevel } from '@kiskadee/core';

export default {
  subtle: {
    // Subtle track: 0–15 (every 1%), then 20, 25, 30
    0: [0, 0, 100, 1], // 0% darkness (white/lightest)
    1: [0, 0, 99, 1], // 1% darkness
    2: [0, 0, 98, 1], // 2% darkness
    3: [0, 0, 97, 1], // 3% darkness
    4: [0, 0, 96, 1], // 4% darkness
    5: [0, 0, 95, 1], // 5% darkness
    6: [0, 0, 94, 1], // 6% darkness
    7: [0, 0, 93, 1], // 7% darkness
    8: [0, 0, 92, 1], // 8% darkness
    9: [0, 0, 91, 1], // 9% darkness
    10: [0, 0, 90, 1], // 10% darkness
    11: [0, 0, 89, 1], // 11% darkness
    12: [0, 0, 88, 1], // 12% darkness
    13: [0, 0, 87, 1], // 13% darkness
    14: [0, 0, 86, 1], // 14% darkness
    15: [0, 0, 85, 1], // 15% darkness
    20: [0, 0, 77.65, 1], // 20% darkness - OVERRIDDEN: generated #C2C2C2 was replaced by #C6C6C6
    25: [0, 0, 72, 1], // 25% darkness
    30: [0, 0, 68, 1] // 30% darkness
  },
  vivid: {
    // Vivid track: 35–100 every 5% darkness (35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100)
    // Original color darkness ≈ 100% → usage anchor emphasis 100
    35: [0, 0, 64, 1], // 36% darkness
    40: [0, 0, 59, 1], // 41% darkness
    45: [0, 0, 55, 1], // 45% darkness
    50: [0, 0, 50, 1], // 50% darkness
    55: [0, 0, 45, 1], // 55% darkness
    60: [0, 0, 40, 1], // 60% darkness
    65: [0, 0, 35, 1], // 65% darkness
    70: [0, 0, 30, 1], // 70% darkness
    75: [0, 0, 25, 1], // 75% darkness
    80: [0, 0, 20, 1], // 80% darkness
    85: [0, 0, 15, 1], // 85% darkness
    90: [0, 0, 10, 1], // 90% darkness
    95: [0, 0, 5, 1], // 95% darkness
    100: [0, 0, 0, 1] // 100% darkness - original color emphasis (#000) - USAGE ANCHOR
  }
} as EmphasisLevel;
