// Generated by generateColorScaleArtifact('#000', true, {
//   20: '#c6c6c6',
// }, false)

import type { KiskadeeHexScale } from '@kiskadee/core';

export default {
  0: '#ffffff',
  1: '#fcfcfc',
  2: '#fafafa',
  3: '#f7f7f7',
  4: '#f5f5f5',
  5: '#f2f2f2',
  6: '#f0f0f0',
  7: '#ededed',
  8: '#ebebeb',
  9: '#e8e8e8',
  10: '#e6e6e6',
  12: '#e0e0e0',
  14: '#dbdbdb',
  16: '#d5d5d5',
  18: '#cdcdcd',
  20: '#c6c6c6',
  22: '#c0c0c0',
  24: '#bababa',
  26: '#b6b6b6',
  28: '#b1b1b1',
  30: '#adadad',
  35: '#a3a3a3',
  40: '#969696',
  45: '#8c8c8c',
  50: '#808080',
  55: '#737373',
  60: '#666666',
  65: '#595959',
  70: '#4d4d4d',
  75: '#404040',
  80: '#333333',
  85: '#262626',
  90: '#1a1a1a',
  95: '#0d0d0d',
  99: '#000000',
  100: '#000000'
} as KiskadeeHexScale;
