/**
 * Generate Next.js showcase registries from @kiskadee/web-builder manifests.
 *
 * This script reads metadata produced by the web-builder (one manifest.json
 * per preset under packages/web-builder/build/**) and generates TypeScript
 * registries under packages/showcase/registry:
 *
 *   - templates.registry.generated.ts
 *   - css.registry.generated.ts
 *
 * These files are then re-exported by the hand-written registry modules so
 * that the showcase automatically picks up any new presets without manual
 * updates.
 */

import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

type Manifest = {
  key: string;
  displayName: string;
  author: string | null;
  schemaName: string | null;
  version: [number, number, number] | null;
  segments: string[];
  themes: Record<string, string[]>;
  components?: Record<string, unknown>;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// When this script lived at the monorepo root, __dirname already pointed to
// the repo root and we could resolve "packages/web-builder/build" directly.
// After moving the script to packages/web-builder/scripts, we must:
// - treat the web-builder package root as the source base (build directory),
// - and still resolve the showcase registry target relative to the monorepo root.

// packages/web-builder/scripts -> packages/web-builder
const webBuilderRoot = path.resolve(__dirname, '..');

// Source of manifests: packages/web-builder/build
const webBuilderBuildDir = path.resolve(webBuilderRoot, 'build');

// Monorepo root: packages/web-builder -> ../.. -> <repoRoot>
const repoRoot = path.resolve(webBuilderRoot, '..', '..');

// Base URL used by the Next.js app to serve build artifacts
const showcaseBuildBase = '/build';

// Target directory for generated registries in the showcase app
// NOTE: The registry now lives at packages/showcase/registry (outside app/)
const showcaseRegistryDir = path.resolve(repoRoot, 'packages', 'showcase', 'registry');
const showcaseGeneratedRegistryDir = path.resolve(showcaseRegistryDir, 'generated');

async function existsDir(dir: string): Promise<boolean> {
  try {
    const dirStats = await stat(dir);
    return dirStats.isDirectory();
  } catch {
    return false;
  }
}

async function discoverManifests(): Promise<Manifest[]> {
  if (!(await existsDir(webBuilderBuildDir))) {
    console.error('[generate-showcase-registry] Build directory not found:', webBuilderBuildDir);
    console.error(
      'Make sure you have run the @kiskadee/web-builder build beforehand (run-build.ts).'
    );
    process.exitCode = 1;
    return [];
  }

  const entries = await readdir(webBuilderBuildDir, { withFileTypes: true });

  const manifests: Manifest[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const dir = path.join(webBuilderBuildDir, entry.name);
    const manifestPath = path.join(dir, 'manifest.json');
    if (!existsSync(manifestPath)) continue;

    try {
      const raw = await readFile(manifestPath, 'utf8');
      const parsed = JSON.parse(raw) as Manifest;
      if (!parsed || typeof parsed.key !== 'string') continue;
      manifests.push(parsed);
    } catch (error) {
      console.warn('[generate-showcase-registry] Failed to read manifest for', entry.name, error);
    }
  }

  return manifests;
}

function generateTemplatesRegistrySource(manifests: Manifest[]): string {
  const lines = [];

  lines.push('// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.');
  lines.push(
    '// Generated by scripts/generate-showcase-registry.ts based on web-builder manifests.'
  );
  lines.push(
    "import type { ComponentClassNameMapJSON, ExtraArtifactsJSON } from '@kiskadee/web-builder/types';"
  );
  lines.push(
    "import { loadJsonFromBuild } from '@/utils/build-artifacts.client';"
  );
  lines.push('');
  lines.push('type ClassNamesModuleLike = { default: ComponentClassNameMapJSON };');
  lines.push('');
  lines.push('// Helper that wraps build JSON loading and returns a "module-like" object');
  lines.push('// compatible with the existing code in app/providers.tsx.');
  lines.push('function loadJsonModule(relativePath: string): Promise<ClassNamesModuleLike> {');
  lines.push(
    '  return loadJsonFromBuild<ComponentClassNameMapJSON>(relativePath, { required: true }).then((json) => ({ default: json }));'
  );
  lines.push('}');
  lines.push('');
  lines.push('// Helper to load extra.<segment>.<theme>.kiskadee.json files with proper typing.');
  lines.push('function loadExtraJson(relativePath: string): Promise<ExtraArtifactsJSON> {');
  lines.push('  return loadJsonFromBuild<ExtraArtifactsJSON>(relativePath, {');
  lines.push('    required: false,');
  lines.push('    fallback: {} as ExtraArtifactsJSON,');
  lines.push('  });');
  lines.push('}');
  lines.push('');

  // coreMaps
  lines.push('export const coreMaps = {');
  for (const m of manifests) {
    const corePath = `${m.key}/core.kiskadee.json`;
    lines.push(`  '${m.key}': () => loadJsonModule('${corePath}'),`);
  }
  lines.push('} as const;');
  lines.push('');

  // paletteMaps
  lines.push('export const paletteMaps = {');
  for (const m of manifests) {
    for (const segment of m.segments || []) {
      const themes = m.themes?.[segment];
      if (!themes || !themes.length) continue;
      for (const theme of themes) {
        const key = `${m.key}|${segment}|${theme}`;
        const file = `${segment}.${theme}.kiskadee.json`;
        const rel = `${m.key}/${file}`;
        lines.push(`  '${key}': () => loadJsonModule('${rel}'),`);
      }
    }
  }
  lines.push('} as const;');
  lines.push('');

  // extraMaps: maps designSystem|segment|theme to loader of extra.<segment>.<theme>.kiskadee.json
  lines.push('export const extraMaps = {');
  for (const m of manifests) {
    for (const segment of m.segments || []) {
      const themes = m.themes?.[segment];
      if (!themes || !themes.length) continue;
      for (const theme of themes) {
        const key = `${m.key}|${segment}|${theme}`;
        const file = `extra.${segment}.${theme}.kiskadee.json`;
        // Only generate an entry if the corresponding extra JSON file
        // actually exists in the web-builder build output. This avoids
        // issuing fetch requests that would 404 for design systems that
        // don't define extra artifacts for a given segment/theme.
        const physicalPath = path.join(webBuilderBuildDir, m.key, file);
        if (!existsSync(physicalPath)) continue;
        const rel = `${m.key}/${file}`;
        lines.push(`  '${key}': () => loadExtraJson('${rel}'),`);
      }
    }
  }
  lines.push('} as const;');
  lines.push('');

  // paletteIndex
  lines.push('export const paletteIndex = {');
  for (const m of manifests) {
    const segs = m.segments || [];
    const themesBySegmentEntries = [];
    for (const seg of segs) {
      const themes = m.themes?.[seg] || [];
      if (!themes.length) continue;
      const themesList = themes.map((t) => `'${t}'`).join(', ');
      themesBySegmentEntries.push(`      ${JSON.stringify(seg)}: [${themesList}]`);
    }

    lines.push(`  '${m.key}': {`);
    lines.push(`    segments: [${segs.map((s) => `'${s}'`).join(', ')}],`);
    if (themesBySegmentEntries.length) {
      lines.push('    themesBySegment: {');
      lines.push(themesBySegmentEntries.join(',\n'));
      lines.push('    }');
    } else {
      lines.push('    themesBySegment: {}');
    }
    lines.push('  },');
  }
  lines.push('} as const;');
  lines.push('');

  // designSystemList (simplified manifest: key + displayName)
  lines.push('export type DesignSystemListEntry = import(\'@kiskadee/web-builder/types\').DesignSystemListEntry;');
  lines.push('');
  lines.push('export const designSystemList: DesignSystemListEntry[] = [');
  for (const m of manifests) {
    const displayName = m.displayName || m.key;
    lines.push(`  { key: '${m.key}', displayName: ${JSON.stringify(displayName)} },`);
  }
  lines.push('];');
  lines.push('');

  // designSystemMeta
  lines.push('export const designSystemMeta = {');
  for (const m of manifests) {
    const displayName = m.displayName || m.key;
    const entry = {
      displayName,
      components: m.components
    };
    lines.push(`  '${m.key}': ${JSON.stringify(entry)},`);
  }
  lines.push('} as const;');
  lines.push('');

  return lines.join('\n');
}

function generateCssRegistrySource(manifests: Manifest[]): string {
  const lines = [];

  lines.push('// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.');
  lines.push(
    '// Generated by scripts/generate-showcase-registry.ts based on web-builder manifests.'
  );
  lines.push('');
  lines.push('export const cssPaths = {');
  for (const m of manifests) {
    const coreCss = `${showcaseBuildBase}/${m.key}/core.kiskadee.css`;
    const effectsCss = `${showcaseBuildBase}/${m.key}/effects.kiskadee.css`;
    const globalTokensFile = 'tokens.kiskadee.css';
    const globalTokensPhysicalPath = path.join(webBuilderBuildDir, m.key, globalTokensFile);
    const globalTokensCss = existsSync(globalTokensPhysicalPath)
      ? `${showcaseBuildBase}/${m.key}/${globalTokensFile}`
      : null;

    lines.push(`  '${m.key}': {`);
    lines.push(`    core: '${coreCss}',`);
    lines.push(`    effects: '${effectsCss}',`);
    lines.push(`    tokens: ${globalTokensCss ? `'${globalTokensCss}'` : 'null'},`);
    lines.push('    palettes: {');

    for (const segment of m.segments || []) {
      const themes = m.themes?.[segment] || [];
      for (const theme of themes) {
        const paletteKey = `${segment}|${theme}`;
        const file = `${segment}.${theme}.kiskadee.css`;
        const url = `${showcaseBuildBase}/${m.key}/${file}`;
        lines.push(`      '${paletteKey}': '${url}',`);
      }
    }

    lines.push('    },');
    lines.push('    tokenPalettes: {');

    for (const segment of m.segments || []) {
      const themes = m.themes?.[segment] || [];
      for (const theme of themes) {
        const tokenPaletteKey = `${segment}|${theme}`;
        const tokenFile = `tokens.${segment}.${theme}.kiskadee.css`;
        const tokenPhysicalPath = path.join(webBuilderBuildDir, m.key, tokenFile);
        if (!existsSync(tokenPhysicalPath)) continue;
        const tokenUrl = `${showcaseBuildBase}/${m.key}/${tokenFile}`;
        lines.push(`      '${tokenPaletteKey}': '${tokenUrl}',`);
      }
    }

    lines.push('    }');
    lines.push('  },');
  }
  lines.push('} as const;');
  lines.push('');
  lines.push('export type CssRegistry = typeof cssPaths;');
  lines.push('');

  return lines.join('\n');
}

function generateColorsRegistrySource(manifests: Manifest[]): string {
  const lines = [];

  lines.push('// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.');
  lines.push(
    '// Generated by scripts/generate-showcase-registry.ts based on web-builder manifests.'
  );
  lines.push("import { loadJsonFromBuild } from '@/utils/build-artifacts.client';");
  lines.push('');

  lines.push('export type ColorsJson = any;');
  lines.push('export type ColorScaleJson = Record<string, Record<string, string>>;');
  lines.push('');

  lines.push('// Map: designSystemKey -> loader for <ds>/colors.json');
  lines.push('export const colorsMaps = {');
  for (const m of manifests) {
    const rel = `${m.key}/colors.json`;
    lines.push(`  '${m.key}': () => loadJsonFromBuild<ColorsJson>('${rel}', { required: true }),`);
  }
  lines.push('} as const;');
  lines.push('');

  lines.push('// Helper to load a primitive color scale file referenced by colors.json');
  lines.push('// (e.g. fileName = "purple.light.json" -> /build/<ds>/colors/purple.light.json)');
  lines.push('export function loadColorScaleFromBuild(designSystemKey: string, fileName: string) {');
  lines.push(
    '  return loadJsonFromBuild<ColorScaleJson>(`${designSystemKey}/colors/${fileName}`, { required: true });'
  );
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

async function writeFileIfChanged(targetPath: string, content: string): Promise<void> {
  let existing: string | null = null;
  try {
    existing = await readFile(targetPath, 'utf8');
  } catch {
    // ignore
  }

  if (existing === content) return;

  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, content, 'utf8');
  // console.log('[generate-showcase-registry] Wrote', path.relative(repoRoot, targetPath));
}

async function main(): Promise<void> {
  const manifests = await discoverManifests();
  if (!manifests.length) {
    console.warn('[generate-showcase-registry] No manifests found under', webBuilderBuildDir);
    return;
  }

  const templatesTs = generateTemplatesRegistrySource(manifests);
  const cssTs = generateCssRegistrySource(manifests);
  const colorsTs = generateColorsRegistrySource(manifests);

  const templatesTarget = path.resolve(
    showcaseGeneratedRegistryDir,
    'design-systems.registry.generated.ts'
  );
  const cssTarget = path.resolve(showcaseGeneratedRegistryDir, 'css.registry.generated.ts');
  const colorsTarget = path.resolve(showcaseGeneratedRegistryDir, 'colors.registry.generated.ts');

  await writeFileIfChanged(templatesTarget, templatesTs);
  await writeFileIfChanged(cssTarget, cssTs);
  await writeFileIfChanged(colorsTarget, colorsTs);
}

main().catch((error) => {
  console.error('[generate-showcase-registry] Unexpected error:', error);
  process.exitCode = 1;
});
