// Generated by generateColorScaleArtifact('#fff', true, {}, true)

import type { EmphasisLevel } from '@kiskadee/core';

export default {
  subtle: {
    // Subtle track: 0–10 (every 1%), then 15, 20, 25, 30
    0: [0, 0, 0, 1], // 100% darkness (black/darkest)
    1: [0, 0, 1, 1], // 99% darkness
    2: [0, 0, 2, 1], // 98% darkness
    3: [0, 0, 3, 1], // 97% darkness
    4: [0, 0, 4, 1], // 96% darkness
    5: [0, 0, 5, 1], // 95% darkness
    6: [0, 0, 6, 1], // 94% darkness
    7: [0, 0, 7, 1], // 93% darkness
    8: [0, 0, 8, 1], // 92% darkness
    9: [0, 0, 9, 1], // 91% darkness
    10: [0, 0, 10, 1], // 90% darkness
    15: [0, 0, 15, 1], // 85% darkness
    20: [0, 0, 20, 1], // 80% darkness
    25: [0, 0, 25, 1], // 75% darkness
    30: [0, 0, 30, 1] // 70% darkness
  },
  vivid: {
    // Vivid track: 40–100 every 10% darkness (40, 50, 60, 70, 80, 90, 100)
    40: [0, 0, 40, 1], // 60% darkness
    50: [0, 0, 50, 1], // 50% darkness
    60: [0, 0, 60, 1], // 40% darkness
    70: [0, 0, 70, 1], // 30% darkness
    80: [0, 0, 80, 1], // 20% darkness
    90: [0, 0, 90, 1], // 10% darkness
    100: [0, 0, 100, 1] // 0% darkness (white/lightest)
  }
} as EmphasisLevel;
