// Generated by generateColorScaleWithLog('#0F6CBD', true, {}, {
//   anchorTone: 60,
//   hueShiftTotal: -2.25,
//   saturationDropTotal: 7.93,
//   lightnessStep: 6.4,
// })

import type { EmphasisLevel } from '@kiskadee/core';

export default {
  subtle: {
    // Subtle track: 0–10 (every 1%), then 15, 20, 25, 30
    0: [0, 0, 100, 1], // 0% darkness (white/lightest)
    1: [207.93, 85.29, 99, 1], // 1% darkness
    2: [207.93, 85.29, 98, 1], // 2% darkness
    3: [207.93, 85.29, 97, 1], // 3% darkness
    4: [207.93, 85.29, 96, 1], // 4% darkness
    5: [207.93, 85.29, 95, 1], // 5% darkness
    6: [207.93, 85.29, 94, 1], // 6% darkness
    7: [207.93, 85.29, 93, 1], // 7% darkness
    8: [207.93, 85.29, 92, 1], // 8% darkness
    9: [207.93, 85.29, 91, 1], // 9% darkness
    10: [207.93, 85.29, 90, 1], // 10% darkness
    15: [207.93, 85.29, 85, 1], // 15% darkness
    20: [207.93, 85.29, 80, 1], // 20% darkness
    25: [207.93, 85.29, 75, 1], // 25% darkness
    30: [207.93, 85.29, 70, 1] // 30% darkness
  },
  vivid: {
    // Vivid track: 40–100 every 10% darkness (40, 50, 60, 70, 80, 90, 100)
    // Original color darkness ≈ 60% → usage anchor emphasis 60
    40: [207.93, 85.29, 60, 1], // 40% darkness
    50: [207.93, 85.29, 50, 1], // 50% darkness
    60: [207.93, 85.29, 40, 1], // 60% darkness - original color emphasis (#0F6CBD) - USAGE ANCHOR
    70: [207.18, 82.65, 33.6, 1], // 66.4% darkness
    80: [206.43, 80, 27.2, 1], // 72.8% darkness
    90: [205.68, 77.36, 20.8, 1], // 79.2% darkness
    100: [0, 0, 0, 1] // 100% darkness (black/darkest)
  }
} as EmphasisLevel;
