// Generated by generateColorScaleArtifact('#9780F7', false, {
//   25: '#9780F7',
// }, false)

import type { EmphasisLevel } from '@kiskadee/core';

export default {
  subtle: {
    // Subtle track: 0–15 (every 1%), then 20, 25, 30
    0: [0, 0, 100, 1], // 0% darkness (white/lightest)
    1: [251.6, 88.15, 99, 1], // 1% darkness
    2: [251.6, 88.15, 98, 1], // 2% darkness
    3: [251.6, 88.15, 97, 1], // 3% darkness
    4: [251.6, 88.15, 96, 1], // 4% darkness
    5: [251.6, 88.15, 95, 1], // 5% darkness
    6: [251.6, 88.15, 94, 1], // 6% darkness
    7: [251.6, 88.15, 93, 1], // 7% darkness
    8: [251.6, 88.15, 92, 1], // 8% darkness
    9: [251.6, 88.15, 91, 1], // 9% darkness
    10: [251.6, 88.15, 90, 1], // 10% darkness
    11: [251.6, 88.15, 89, 1], // 11% darkness
    12: [251.6, 88.15, 88, 1], // 12% darkness
    13: [251.6, 88.15, 87, 1], // 13% darkness
    14: [251.6, 88.15, 86, 1], // 14% darkness
    15: [251.6, 88.15, 85, 1], // 15% darkness
    20: [251.6, 88.15, 80, 1], // 20% darkness
    25: [251.6, 88.15, 73.53, 1], // 25% darkness - OVERRIDDEN: generated #9D87F7 was replaced by #9780F7
    30: [251.6, 88.15, 70, 1] // 30% darkness
  },
  vivid: {
    // Vivid track: 35–100 every 5% darkness (35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100)
    // Input color is very light (L=73.53%), so tone 50 was re-centered to L=50 instead of using the original lightness
    35: [251.6, 88.15, 65, 1],
    40: [251.6, 88.15, 60, 1],
    45: [251.6, 88.15, 55, 1],
    50: [251.6, 88.15, 50, 1], // Re-centered mid tone (L=50) because input color (#9780F7, L=73.53%) is too light to be an anchor
    55: [251.6, 88.15, 45, 1],
    60: [251.6, 88.15, 40, 1],
    65: [251.6, 88.15, 35, 1],
    70: [251.6, 88.15, 30, 1],
    75: [251.6, 88.15, 25, 1],
    80: [251.6, 88.15, 20, 1],
    85: [251.6, 88.15, 15, 1],
    90: [251.6, 88.15, 10, 1],
    95: [251.6, 88.15, 5, 1],
    100: [0, 0, 0, 1]
  }
} as EmphasisLevel;
