// Generated by generateColorScaleArtifact('#8283f6', false, {
//   25: '#8283f6',
// }, false)

import type { KiskadeeHexScale } from '@kiskadee/core';

export default {
  0: '#ffffff',
  1: '#fafaff',
  2: '#f5f6fe',
  3: '#f1f1fe',
  4: '#ececfe',
  5: '#e7e7fd',
  6: '#e2e3fd',
  7: '#dedefd',
  8: '#d9d9fc',
  9: '#d4d5fc',
  10: '#cfd0fc',
  12: '#c6c6fb',
  14: '#bcbdfa',
  16: '#b3b4fa',
  18: '#a9aaf9',
  20: '#a0a1f8',
  22: '#9495f7',
  24: '#8889f7',
  26: '#7e80f6',
  28: '#7779f5',
  30: '#7071f5',
  35: '#585af3',
  40: '#4142f1',
  45: '#292bf0',
  50: '#1113ee',
  55: '#0f11d6',
  60: '#0e0fbe',
  65: '#0c0da7',
  70: '#0a0b8f',
  75: '#090a77',
  80: '#07085f',
  85: '#050647',
  90: '#030430',
  95: '#020218',
  99: '#000000',
  100: '#000000'
} as KiskadeeHexScale;
