// Generated by generateColorScaleArtifact('#8283F6', false, {
//   25: '#8283F6',
// }, false)

import type { EmphasisLevel } from '@kiskadee/core';

export default {
  subtle: {
    // Subtle track: 0–15 (every 1%), then 20, 25, 30
    0: [0, 0, 100, 1], // 0% darkness (white/lightest)
    1: [239.48, 86.57, 99, 1], // 1% darkness
    2: [239.48, 86.57, 98, 1], // 2% darkness
    3: [239.48, 86.57, 97, 1], // 3% darkness
    4: [239.48, 86.57, 96, 1], // 4% darkness
    5: [239.48, 86.57, 95, 1], // 5% darkness
    6: [239.48, 86.57, 94, 1], // 6% darkness
    7: [239.48, 86.57, 93, 1], // 7% darkness
    8: [239.48, 86.57, 92, 1], // 8% darkness
    9: [239.48, 86.57, 91, 1], // 9% darkness
    10: [239.48, 86.57, 90, 1], // 10% darkness
    11: [239.48, 86.57, 89, 1], // 11% darkness
    12: [239.48, 86.57, 88, 1], // 12% darkness
    13: [239.48, 86.57, 87, 1], // 13% darkness
    14: [239.48, 86.57, 86, 1], // 14% darkness
    15: [239.48, 86.57, 85, 1], // 15% darkness
    20: [239.48, 86.57, 80, 1], // 20% darkness
    25: [239.48, 86.57, 73.73, 1], // 25% darkness - OVERRIDDEN: generated #8889F6 was replaced by #8283F6
    30: [239.48, 86.57, 70, 1] // 30% darkness
  },
  vivid: {
    // Vivid track: 35–100 every 5% darkness (35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100)
    // Input color is very light (L=73.73%), so tone 50 was re-centered to L=50 instead of using the original lightness
    35: [239.48, 86.57, 65, 1],
    40: [239.48, 86.57, 60, 1],
    45: [239.48, 86.57, 55, 1],
    50: [239.48, 86.57, 50, 1], // Re-centered mid tone (L=50) because input color (#8283F6, L=73.73%) is too light to be an anchor
    55: [239.48, 86.57, 45, 1],
    60: [239.48, 86.57, 40, 1],
    65: [239.48, 86.57, 35, 1],
    70: [239.48, 86.57, 30, 1],
    75: [239.48, 86.57, 25, 1],
    80: [239.48, 86.57, 20, 1],
    85: [239.48, 86.57, 15, 1],
    90: [239.48, 86.57, 10, 1],
    95: [239.48, 86.57, 5, 1],
    100: [0, 0, 0, 1]
  }
} as EmphasisLevel;
