// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/generate-showcase-registry.cjs based on web-builder manifests.

export const cssPaths = {
  'carbon-1-ibm': {
    core: '/build/carbon-1-ibm/core.kiskadee.css',
    effects: '/build/carbon-1-ibm/effects.kiskadee.css',
    palettes: {
      'default|light': '/build/carbon-1-ibm/default.light.kiskadee.css',
    }
  },
  'fluent-2-kiskadee': {
    core: '/build/fluent-2-kiskadee/core.kiskadee.css',
    effects: '/build/fluent-2-kiskadee/effects.kiskadee.css',
    palettes: {
      'default|light': '/build/fluent-2-kiskadee/default.light.kiskadee.css',
      'default|dark': '/build/fluent-2-kiskadee/default.dark.kiskadee.css',
    }
  },
  'fluent-2-microsoft': {
    core: '/build/fluent-2-microsoft/core.kiskadee.css',
    effects: '/build/fluent-2-microsoft/effects.kiskadee.css',
    palettes: {
      'default|light': '/build/fluent-2-microsoft/default.light.kiskadee.css',
      'default|dark': '/build/fluent-2-microsoft/default.dark.kiskadee.css',
    }
  },
  'ios-26-apple': {
    core: '/build/ios-26-apple/core.kiskadee.css',
    effects: '/build/ios-26-apple/effects.kiskadee.css',
    palettes: {
      'default|light': '/build/ios-26-apple/default.light.kiskadee.css',
    }
  },
  'ios-26-kiskadee': {
    core: '/build/ios-26-kiskadee/core.kiskadee.css',
    effects: '/build/ios-26-kiskadee/effects.kiskadee.css',
    palettes: {
      'default|light': '/build/ios-26-kiskadee/default.light.kiskadee.css',
      'default|dark': '/build/ios-26-kiskadee/default.dark.kiskadee.css',
      'dynamic|light': '/build/ios-26-kiskadee/dynamic.light.kiskadee.css',
      'dynamic|dark': '/build/ios-26-kiskadee/dynamic.dark.kiskadee.css',
    }
  },
  'material-design-3-google': {
    core: '/build/material-design-3-google/core.kiskadee.css',
    effects: '/build/material-design-3-google/effects.kiskadee.css',
    palettes: {
      'default|light': '/build/material-design-3-google/default.light.kiskadee.css',
    }
  },
} as const;

export type CssRegistry = typeof cssPaths;
