// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/generate-showcase-registry.cjs based on web-builder manifests.
import type { ComponentClassNameMap, ExtraArtifactsJSON } from '@kiskadee/web-builder/types';

type ClassNamesModuleLike = { default: ComponentClassNameMap };

// Helper that wraps fetch and returns a "module-like" object compatible
// with the existing code in app/providers.tsx.
function loadJsonModule(path: string): Promise<ClassNamesModuleLike> {
  return fetch(path)
    .then((response) => {
      if (!response.ok) {
        throw new Error(`Failed to load classNamesMap JSON: ${path} (${response.status})`);
      }
      return response.json();
    })
    .then((json) => ({ default: json as ComponentClassNameMap }));
}

// Helper to load extra.<segment>.<theme>.kiskadee.json files with proper typing.
function loadExtraJson(path: string): Promise<ExtraArtifactsJSON> {
  return fetch(path).then((response) => {
    if (response.status === 404) {
      // Extra artifacts are optional; treat 404 as "no extras" and return an empty object.
      return {} as ExtraArtifactsJSON;
    }
    if (!response.ok) {
      throw new Error(`Failed to load extra JSON: ${path} (${response.status})`);
    }
    return response.json() as Promise<ExtraArtifactsJSON>;
  });
}

export const coreMaps = {
  'carbon-1-ibm': () => loadJsonModule('/build/carbon-1-ibm/core.kiskadee.json'),
  'fluent-2-kiskadee': () => loadJsonModule('/build/fluent-2-kiskadee/core.kiskadee.json'),
  'fluent-2-microsoft': () => loadJsonModule('/build/fluent-2-microsoft/core.kiskadee.json'),
  'ios-26-apple': () => loadJsonModule('/build/ios-26-apple/core.kiskadee.json'),
  'ios-26-kiskadee': () => loadJsonModule('/build/ios-26-kiskadee/core.kiskadee.json'),
  'material-design-3-google': () =>
    loadJsonModule('/build/material-design-3-google/core.kiskadee.json')
} as const;

export const paletteMaps = {
  'carbon-1-ibm|default|light': () =>
    loadJsonModule('/build/carbon-1-ibm/default.light.kiskadee.json'),
  'fluent-2-kiskadee|default|light': () =>
    loadJsonModule('/build/fluent-2-kiskadee/default.light.kiskadee.json'),
  'fluent-2-kiskadee|default|dark': () =>
    loadJsonModule('/build/fluent-2-kiskadee/default.dark.kiskadee.json'),
  'fluent-2-microsoft|default|light': () =>
    loadJsonModule('/build/fluent-2-microsoft/default.light.kiskadee.json'),
  'fluent-2-microsoft|default|dark': () =>
    loadJsonModule('/build/fluent-2-microsoft/default.dark.kiskadee.json'),
  'ios-26-apple|default|light': () =>
    loadJsonModule('/build/ios-26-apple/default.light.kiskadee.json'),
  'ios-26-kiskadee|default|light': () =>
    loadJsonModule('/build/ios-26-kiskadee/default.light.kiskadee.json'),
  'ios-26-kiskadee|default|dark': () =>
    loadJsonModule('/build/ios-26-kiskadee/default.dark.kiskadee.json'),
  'ios-26-kiskadee|dynamic|light': () =>
    loadJsonModule('/build/ios-26-kiskadee/dynamic.light.kiskadee.json'),
  'ios-26-kiskadee|dynamic|dark': () =>
    loadJsonModule('/build/ios-26-kiskadee/dynamic.dark.kiskadee.json'),
  'material-design-3-google|default|light': () =>
    loadJsonModule('/build/material-design-3-google/default.light.kiskadee.json')
} as const;

export const extraMaps = {
  'carbon-1-ibm|default|light': () =>
    loadExtraJson('/build/carbon-1-ibm/extra.default.light.kiskadee.json'),
  'fluent-2-kiskadee|default|light': () =>
    loadExtraJson('/build/fluent-2-kiskadee/extra.default.light.kiskadee.json'),
  'fluent-2-kiskadee|default|dark': () =>
    loadExtraJson('/build/fluent-2-kiskadee/extra.default.dark.kiskadee.json'),
  'fluent-2-microsoft|default|light': () =>
    loadExtraJson('/build/fluent-2-microsoft/extra.default.light.kiskadee.json'),
  'fluent-2-microsoft|default|dark': () =>
    loadExtraJson('/build/fluent-2-microsoft/extra.default.dark.kiskadee.json'),
  'ios-26-kiskadee|default|light': () =>
    loadExtraJson('/build/ios-26-kiskadee/extra.default.light.kiskadee.json'),
  'ios-26-kiskadee|dynamic|light': () =>
    loadExtraJson('/build/ios-26-kiskadee/extra.dynamic.light.kiskadee.json')
} as const;

export const paletteIndex = {
  'carbon-1-ibm': {
    segments: ['default'],
    themesBySegment: {
      default: ['light']
    }
  },
  'fluent-2-kiskadee': {
    segments: ['default'],
    themesBySegment: {
      default: ['light', 'dark']
    }
  },
  'fluent-2-microsoft': {
    segments: ['default'],
    themesBySegment: {
      default: ['light', 'dark']
    }
  },
  'ios-26-apple': {
    segments: ['default'],
    themesBySegment: {
      default: ['light']
    }
  },
  'ios-26-kiskadee': {
    segments: ['default', 'dynamic'],
    themesBySegment: {
      default: ['light', 'dark'],
      dynamic: ['light', 'dark']
    }
  },
  'material-design-3-google': {
    segments: ['default'],
    themesBySegment: {
      default: ['light']
    }
  }
} as const;

export const designSystemMeta = {
  'carbon-1-ibm': {
    displayName: 'Carbon by IBM',
    components: {
      button: {
        scale: {
          's:sm:2': true,
          's:sm:1': true,
          's:md:1': true,
          's:lg:1': true,
          's:lg:2': true,
          's:lg:3': true
        },
        state: {
          primary: {
            solid: { rest: true, hover: true, focus: true, pressed: true, disabled: true }
          }
        }
      }
    }
  },
  'fluent-2-kiskadee': {
    displayName: 'Fluent 2 by Kiskadee',
    components: {
      button: {
        scale: { 's:sm:1': true, 's:md:1': true, 's:lg:1': true },
        state: {
          primary: {
            solid: {
              rest: true,
              hover: true,
              focus: true,
              pressed: true,
              disabled: true,
              selected: true
            }
          }
        }
      }
    }
  },
  'fluent-2-microsoft': {
    displayName: 'Fluent 2 by Microsoft',
    components: {
      button: {
        scale: { 's:sm:1': true, 's:md:1': true, 's:lg:1': true },
        state: {
          primary: {
            solid: {
              rest: true,
              hover: true,
              focus: true,
              pressed: true,
              disabled: true,
              selected: true
            }
          }
        }
      }
    }
  },
  'ios-26-apple': {
    displayName: 'iOS 26 by Apple',
    components: {
      button: {
        scale: { 's:md:1': true },
        state: {
          primary: {
            soft: {
              rest: true,
              hover: true,
              focus: true,
              pressed: true,
              disabled: true,
              selected: true
            },
            solid: {
              rest: true,
              hover: true,
              pressed: true,
              disabled: true,
              focus: true,
              selected: true
            }
          }
        }
      }
    }
  },
  'ios-26-kiskadee': {
    displayName: 'iOS 26 by Kiskadee',
    components: {
      button: {
        scale: { 's:sm:1': true, 's:md:1': true, 's:lg:1': true },
        state: {
          primary: {
            soft: {
              rest: true,
              hover: true,
              focus: true,
              pressed: true,
              disabled: true,
              selected: true
            },
            solid: { rest: true, hover: true, focus: true, pressed: true, disabled: true }
          },
          neutral: {
            soft: {
              rest: true,
              hover: true,
              focus: true,
              pressed: true,
              disabled: true,
              selected: true
            }
          },
          redLike: {
            soft: {
              rest: true,
              hover: true,
              focus: true,
              pressed: true,
              disabled: true,
              selected: true
            },
            solid: { rest: true, hover: true, pressed: true, disabled: true, focus: true }
          }
        }
      }
    }
  },
  'material-design-3-google': {
    displayName: 'Material Design 3 by Google',
    components: {
      button: {
        scale: { 's:sm:1': true, 's:md:1': true, 's:lg:1': true, 's:lg:2': true, 's:lg:3': true },
        state: {
          primary: {
            soft: {
              rest: true,
              hover: true,
              pressed: true,
              disabled: true,
              focus: true,
              selected: true
            },
            solid: {
              rest: true,
              hover: true,
              pressed: true,
              disabled: true,
              focus: true,
              selected: true
            }
          }
        }
      }
    }
  }
} as const;
