import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type {
  ComponentClassNameMap,
  ComponentClassNameMapSplit
} from '../phase-5-generate-class-names-map/generateClassNamesMap';

/**
 * Phase 6 - Persist build artifacts generated by previous phases.
 *
 * New naming convention (per template directory):
 * - Core CSS:            core.kiskadee.css
 * - Effects CSS:         effects.kiskadee.css (optional)
 * - Palette CSS:         <segment>.<theme>.kiskadee.css
 * - Core class map JSON: core.kiskadee.json
 * - Palette class map:   <segment>.<theme>.kiskadee.json
 */
export async function persistBuildArtifacts(
  cssGenerated:
    | string
    | {
        coreCss: string;
        effectsCss?: string;
        palettes: Record<string, string>;
      },
  classNamesMap: ComponentClassNameMap | ComponentClassNameMapSplit,
  outDirName?: string
): Promise<void> {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);

  // Ensure build dir exists
  const baseBuildDir = resolve(__dirname, '..', '..', 'build');
  const buildDir = outDirName ? resolve(baseBuildDir, outDirName) : baseBuildDir;
  await mkdir(buildDir, { recursive: true });

  // Persist CSS (core and optional palettes)
  if (typeof cssGenerated === 'string') {
    const outCssFile = resolve(buildDir, 'core.kiskadee.css');
    await writeFile(outCssFile, cssGenerated, 'utf8');
    console.log(`[web-builder] Core CSS written to: ${outCssFile}`);
  } else {
    const outCssFile = resolve(buildDir, 'core.kiskadee.css');
    await writeFile(outCssFile, cssGenerated.coreCss, 'utf8');
    console.log(`[web-builder] Core CSS written to: ${outCssFile}`);

    // Optionally write effects CSS as a separate file to be imported last
    if (cssGenerated.effectsCss && cssGenerated.effectsCss.trim() !== '') {
      const effectsFile = resolve(buildDir, 'effects.kiskadee.css');
      await writeFile(effectsFile, cssGenerated.effectsCss, 'utf8');
      console.log(`[web-builder] Effects CSS written to: ${effectsFile}`);
    }

    // Write palette CSS files as <segment>.<theme>.kiskadee.css
    for (const paletteName in cssGenerated.palettes) {
      const paletteCss = cssGenerated.palettes[paletteName];
      const paletteFile = resolve(buildDir, `${paletteName}.kiskadee.css`);
      await writeFile(paletteFile, paletteCss, 'utf8');
      console.log(`[web-builder] Palette CSS written to: ${paletteFile}`);
    }
  }

  // Persist classNamesMap as JSON (core + optional per-palette files)
  const maybeSplit = classNamesMap as ComponentClassNameMapSplit;
  if (maybeSplit && 'core' in maybeSplit && 'palettes' in maybeSplit) {
    const coreOut = resolve(buildDir, 'core.kiskadee.json');
    await writeFile(coreOut, JSON.stringify(maybeSplit.core, null, 2), 'utf8');
    console.log(`[web-builder] Class names core map written to: ${coreOut}`);

    for (const paletteName in maybeSplit.palettes) {
      const pOut = resolve(buildDir, `${paletteName}.kiskadee.json`);
      await writeFile(pOut, JSON.stringify(maybeSplit.palettes[paletteName], null, 2), 'utf8');
      console.log(`[web-builder] Class names palette map written to: ${pOut}`);
    }
  } else {
    const classNamesOutFileJson = resolve(buildDir, 'core.kiskadee.json');
    const classNamesJson = JSON.stringify(classNamesMap as ComponentClassNameMap, null, 2);
    await writeFile(classNamesOutFileJson, classNamesJson, 'utf8');
    console.log(`[web-builder] Class names map written to: ${classNamesOutFileJson}`);
  }
}
