import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ComponentClassNameMapJSON, ComponentClassNameMapSplitJSON } from '@kiskadee/core';
import { minifyCss } from '@kiskadee/css-build';
import {
  buildComponentClassMapArtifact,
  getComponentCoreClassMapArtifactPath,
  getComponentPaletteClassMapArtifactPath
} from '../component-artifacts/componentClassMapArtifacts.ts';

const coreClassMapSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'Kiskadee core.kiskadee.json',
  type: 'object',
  properties: {
    $schema: {
      type: 'string',
      description: 'JSON Schema reference for this artifact.'
    }
  },
  additionalProperties: {
    $ref: '#/definitions/component'
  },
  definitions: {
    component: {
      type: 'object',
      additionalProperties: {
        $ref: '#/definitions/element'
      }
    },
    element: {
      type: 'object',
      properties: {
        d: {
          type: 'string',
          description: 'Always-on decorations (space-separated class list).'
        },
        e: {
          type: 'object',
          description: 'Effect buckets (opt-in).',
          properties: {
            af: { type: 'string', description: 'Activation feedback effect.' },
            h: { type: 'string', description: 'Shadow effects.' },
            rr: { type: 'string', description: 'Border radius effects for rounded mode.' },
            rp: { type: 'string', description: 'Border radius effects for pill mode.' },
            rs: { type: 'string', description: 'Border radius effects for square mode.' },
            ts: { type: 'object', description: 'Switch thumb-shrink effect by size key.' }
          },
          additionalProperties: { type: 'string' }
        },
        s: {
          type: 'object',
          description: 'Scale classes by size key.',
          additionalProperties: { type: 'string' }
        },
        rr: {
          type: 'object',
          description: 'Rounded border radius scales by size key.',
          additionalProperties: { type: 'string' }
        },
        rp: {
          type: 'object',
          description: 'Pill border radius scales by size key.',
          additionalProperties: { type: 'string' }
        },
        rs: {
          type: 'object',
          description: 'Square border radius scales by size key.',
          additionalProperties: { type: 'string' }
        },
        c: {
          type: 'object',
          description: 'Color classes by semantic key.',
          additionalProperties: { $ref: '#/definitions/colorClasses' }
        },
        l: {
          type: 'string',
          description: 'Control-state classes (selected).'
        }
      },
      additionalProperties: true
    },
    colorClasses: {
      type: 'object',
      properties: {
        h: { type: 'string', description: 'High emphasis classes.' },
        m: { type: 'string', description: 'Medium emphasis classes.' },
        l: { type: 'string', description: 'Low emphasis classes.' },
        ll: { type: 'string', description: 'Lowest emphasis classes.' }
      },
      additionalProperties: false
    }
  }
} as const;

function hasEntries(value: unknown): value is Record<string, unknown> {
  return (
    typeof value === 'object' &&
    value !== null &&
    !Array.isArray(value) &&
    Object.keys(value).length > 0
  );
}

async function writeComponentClassMapArtifacts(
  buildDir: string,
  classNamesMap: ComponentClassNameMapSplitJSON
): Promise<void> {
  const classMapsDir = resolve(buildDir, 'class-maps');
  await rm(classMapsDir, { recursive: true, force: true });

  for (const [componentName, componentClassMap] of Object.entries(classNamesMap.core)) {
    if (componentName === '$schema' || !hasEntries(componentClassMap)) continue;

    const artifactPath = resolve(buildDir, getComponentCoreClassMapArtifactPath(componentName));
    await mkdir(dirname(artifactPath), { recursive: true });
    await writeFile(
      artifactPath,
      JSON.stringify(buildComponentClassMapArtifact(componentName, componentClassMap), null, 2),
      'utf8'
    );
  }

  for (const [paletteName, paletteMap] of Object.entries(classNamesMap.palettes)) {
    if (!hasEntries(paletteMap)) continue;

    for (const [componentName, componentClassMap] of Object.entries(paletteMap)) {
      if (componentName === '$schema' || !hasEntries(componentClassMap)) continue;

      const artifactPath = resolve(
        buildDir,
        getComponentPaletteClassMapArtifactPath(paletteName, componentName)
      );
      await mkdir(dirname(artifactPath), { recursive: true });
      await writeFile(
        artifactPath,
        JSON.stringify(buildComponentClassMapArtifact(componentName, componentClassMap), null, 2),
        'utf8'
      );
    }
  }
}

/**
 * Phase 6 - Persist build artifacts generated by previous phases.
 *
 * New naming convention (per template directory):
 * - Core CSS:            core.kiskadee.css
 * - Effects CSS:         effects.kiskadee.css (optional)
 * - Palette CSS:         <segment>.<theme>.kiskadee.css
 * - Core class map JSON: core.kiskadee.json
 * - Palette class map:   <segment>.<theme>.kiskadee.json
 */
export async function persistBuildArtifacts(
  cssGenerated:
    | string
    | {
        coreCss: string;
        effectsCss?: string;
        palettes: Record<string, string>;
      },
  classNamesMap: ComponentClassNameMapJSON | ComponentClassNameMapSplitJSON,
  outDirName?: string
): Promise<void> {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);

  // Ensure build dir exists
  const baseBuildDir = resolve(__dirname, '..', '..', 'build');
  const buildDir = outDirName ? resolve(baseBuildDir, outDirName) : baseBuildDir;
  await mkdir(buildDir, { recursive: true });

  // Persist CSS (core and optional palettes)
  if (typeof cssGenerated === 'string') {
    const outCssFile = resolve(buildDir, 'core.kiskadee.css');
    await writeFile(outCssFile, await minifyCss(cssGenerated), 'utf8');
    // console.log(`[web-builder] Core CSS written to: ${outCssFile}`);
  } else {
    const outCssFile = resolve(buildDir, 'core.kiskadee.css');
    await writeFile(outCssFile, await minifyCss(cssGenerated.coreCss), 'utf8');
    // console.log(`[web-builder] Core CSS written to: ${outCssFile}`);

    // Optionally write effects CSS as a separate file to be imported last
    if (cssGenerated.effectsCss && cssGenerated.effectsCss.trim() !== '') {
      const effectsFile = resolve(buildDir, 'effects.kiskadee.css');
      await writeFile(effectsFile, await minifyCss(cssGenerated.effectsCss), 'utf8');
      // console.log(`[web-builder] Effects CSS written to: ${effectsFile}`);
    }

    // Write palette CSS files as <segment>.<theme>.kiskadee.css
    for (const paletteName in cssGenerated.palettes) {
      const paletteCss = cssGenerated.palettes[paletteName];
      const paletteFile = resolve(buildDir, `${paletteName}.kiskadee.css`);
      await writeFile(paletteFile, await minifyCss(paletteCss), 'utf8');
      // console.log(`[web-builder] Palette CSS written to: ${paletteFile}`);
    }
  }

  // Persist classNamesMap as JSON (core + optional per-palette files)
  const maybeSplit = classNamesMap as ComponentClassNameMapSplitJSON;
  if (maybeSplit && 'core' in maybeSplit && 'palettes' in maybeSplit) {
    const coreOut = resolve(buildDir, 'core.kiskadee.json');
    const schemaOut = resolve(buildDir, 'core.kiskadee.schema.json');
    const corePayload = {
      $schema: './core.kiskadee.schema.json',
      ...maybeSplit.core
    };
    await writeFile(coreOut, JSON.stringify(corePayload, null, 2), 'utf8');
    await writeFile(schemaOut, JSON.stringify(coreClassMapSchema, null, 2), 'utf8');
    // console.log(`[web-builder] Class names core map written to: ${coreOut}`);
    await writeComponentClassMapArtifacts(buildDir, maybeSplit);

    for (const paletteName in maybeSplit.palettes) {
      const pOut = resolve(buildDir, `${paletteName}.kiskadee.json`);
      await writeFile(pOut, JSON.stringify(maybeSplit.palettes[paletteName], null, 2), 'utf8');
      // console.log(`[web-builder] Class names palette map written to: ${pOut}`);
    }
  } else {
    const classNamesOutFileJson = resolve(buildDir, 'core.kiskadee.json');
    const schemaOut = resolve(buildDir, 'core.kiskadee.schema.json');
    const classNamesJson = JSON.stringify(
      { $schema: './core.kiskadee.schema.json', ...(classNamesMap as ComponentClassNameMapJSON) },
      null,
      2
    );
    await writeFile(classNamesOutFileJson, classNamesJson, 'utf8');
    await writeFile(schemaOut, JSON.stringify(coreClassMapSchema, null, 2), 'utf8');
    // console.log(`[web-builder] Class names map written to: ${classNamesOutFileJson}`);
  }
}
