// Public types and constants for artifacts generated by @kiskadee/web-builder.
//
// This module is intentionally side-effect free so it can be safely
// imported from other packages (e.g., @kiskadee/showcase) without
// triggering any build logic.

export const SYSTEM_UI_FONT_STACK =
  'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif';

export type {
  ClassNameByElementJSON,
  ColorClasses,
  ComponentClassNameMapJSON,
  ComponentClassNameMapSplitJSON
} from '@kiskadee/core';
export type { FontStack } from './src/utils/fontFamily';
export { toCssFontFamily } from './src/utils/fontFamily';

export type DesignSystemListEntry = {
  key: string;
  displayName: string;
};

// JSON structure produced by phase-8 writeExtraArtifacts step.
//
// This artifact is intentionally minimal and now only exposes
// optional showcase background color per design system/segment/theme.
export type ExtraArtifactsJSON = {
  background?: string;
};

// Manifest types (phase-7 publishMetadata) describing high-level
// capabilities by design system.
export type {
  Manifest,
  ManifestComponent,
  ManifestComponentState
} from './src/phase-7-publish-metadata/manifestTypes';
