// Public types for artifacts generated by @kiskadee/web-builder.
//
// This module is intentionally side-effect free so it can be safely
// imported from other packages (e.g., @kiskadee/showcase) without
// triggering any build logic.

export type {
  ComponentClassNameMap,
  ComponentClassNameMapSplit
} from './src/phase-5-generate-class-names-map/generateClassNamesMap';
