// Public types and constants for artifacts generated by @kiskadee/web-builder.
//
// This module is intentionally side-effect free so it can be safely
// imported from other packages (e.g., @kiskadee/showcase) without
// triggering any build logic.

export const SYSTEM_UI_FONT_STACK =
  'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif';

export type {
  ClassNameByElementJSON,
  ColorClasses,
  ComponentClassNameMapJSON,
  ComponentClassNameMapSplitJSON,
  FontStack
} from '@kiskadee/core';
export type {
  BrandPackBuildManifest,
  BrandPackPaletteArtifact
} from './src/brand-packs/brandPackArtifacts.ts';
export {
  BRAND_PACK_BUILD_CONTRACT,
  BRAND_PACK_BUILD_FORMAT_VERSION
} from './src/brand-packs/brandPackArtifacts.ts';
export type {
  CardCanonicalSurfacesPayload,
  CardComponentArtifactJSON,
  ResolvedCardCanonicalSurface
} from './src/component-artifacts/cardComponentArtifact.ts';
export type { ComponentClassMapArtifactJSON } from './src/component-artifacts/componentClassMapArtifacts.ts';
export type { SliderComponentArtifactJSON } from './src/component-artifacts/sliderComponentArtifact.ts';
export type { SwitchComponentArtifactJSON } from './src/component-artifacts/switchComponentArtifact.ts';
export type { TabsComponentArtifactJSON } from './src/component-artifacts/tabsComponentArtifact.ts';
export type { TextFieldComponentArtifactJSON } from './src/component-artifacts/textFieldComponentArtifact.ts';
export {
  SYSTEM_MONOSPACE_FONT_STACK,
  toCssFontFamily
} from './src/utils/fontFamily.ts';

export type DesignSystemListEntry = {
  key: string;
  displayName: string;
};

// JSON structure produced by phase-8 writeExtraArtifacts step.
//
// This artifact is intentionally minimal and now only exposes
// optional showcase background color per design system/segment/theme.
export type ExtraArtifactsJSON = {
  background?: string;
};

// Manifest types (phase-7 publishMetadata) describing high-level
// capabilities by design system.
export type {
  Manifest,
  ManifestComponent,
  ManifestComponentState,
  ManifestFonts,
  ManifestTypography
} from './src/phase-7-publish-metadata/manifestTypes.ts';
export type {
  TypographyArtifact,
  TypographyArtifactProfile,
  TypographyArtifactUsage
} from './src/typography/typographyArtifact.ts';
export { TYPOGRAPHY_ARTIFACT_PATH } from './src/typography/typographyArtifact.ts';
