import { readFileSync } from 'node:fs';
import type { MockInstance } from 'vitest';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { convertHslaToHex } from '@kiskadee/core';
import { generateColorScale, generateColorScaleWithLog } from './generate-color-scale';

describe('generateColorScale', () => {
  it('creates a canonical scale when prioritizeLightnessScale is true', () => {
    const { soft, solid } = generateColorScale('#0F6CBD', true);

    // Soft track extremes
    expect(soft[0]).toEqual([0, 0, 100, 1]);

    // Solid track canonical mapping: index ≈ darkness%. Hue and saturation are
    // now clamped to two decimal places by hexToHSLA.
    expect(solid[40]).toEqual([207.93, 85.29, 60, 1]);
    expect(solid[50]).toEqual([207.93, 85.29, 50, 1]);
    expect(solid[60]).toEqual([207.93, 85.29, 40, 1]);
    expect(solid[70]).toEqual([207.93, 85.29, 30, 1]);
    expect(solid[80]).toEqual([207.93, 85.29, 20, 1]);
    expect(solid[90]).toEqual([207.93, 85.29, 10, 1]);

    // Solid darkest extreme is absolute black
    expect(solid[100]).toEqual([0, 0, 0, 1]);
  });

  it('keeps the input color lightness at tone 50 when prioritizeLightnessScale is false', () => {
    const { soft, solid } = generateColorScale('#0F6CBD', false);

    // Still enforce absolute extremes
    expect(soft[0]).toEqual([0, 0, 100, 1]);
    expect(solid[100]).toEqual([0, 0, 0, 1]);

    // Anchor (tone 50) must preserve the original lightness (L=40 for #0F6CBD)
    expect(solid[50]?.[2]).toBe(40);
  });

  it('re-centers anchor lightness to 50 when the input color is too light to be an anchor', () => {
    const { soft, solid } = generateColorScale('#FFFFFF', false);

    // Still enforce absolute extremes
    expect(soft[0]).toEqual([0, 0, 100, 1]);
    expect(solid[100]).toEqual([0, 0, 0, 1]);

    // For very light inputs (L>70), tone 50 should be re-centered to L=50
    expect(solid[50]?.[2]).toBe(50);
  });

  it('rounds arbitrary lightness to the nearest dark tone bucket', () => {
    // This color was chosen so that its HSLA lightness is approximately 33%,
    // meaning its darkness (~67%) sits between the canonical dark tones 60 and 70.
    // In the Kiskadee model, darkness 67 should snap to tone 70 (70% darkness).
    const { solid } = generateColorScale('#135FA3', true);

    // Tone 70 must be darker than tone 60 and lighter than tone 80, reflecting
    // that 67% darkness has been rounded to the 70 bucket.
    const l60 = solid[60]?.[2] ?? 0;
    const l70 = solid[70]?.[2] ?? 0;
    const l80 = solid[80]?.[2] ?? 0;

    expect(l60).toBeGreaterThan(l70);
    expect(l70).toBeGreaterThan(l80);
  });
});

describe('generateColorScaleWithLog', () => {
  let logSpy: MockInstance;

  beforeEach(() => {
    logSpy = vi.spyOn(console, 'log').mockImplementation(() => undefined);
  });

  afterEach(() => {
    logSpy.mockRestore();
  });

  it('applies tone overrides without changing absolute extremes 0 and 100', () => {
    const overrides = {
      0: '#FF0000', // should be ignored (absolute white is enforced)
      70: '#115EA3', // should override solid[70]
      100: '#00FF00' // should be ignored (absolute black is enforced)
    } as const;

    const tracks = generateColorScaleWithLog('#0F6CBD', true, overrides);

    // Soft[0] and solid[100] must remain absolute white/black
    expect(tracks.soft[0]).toEqual([0, 0, 100, 1]);
    expect(tracks.solid[100]).toEqual([0, 0, 0, 1]);

    // Solid[70] must reflect the overridden Fluent tone (#115EA3). We do not
    // assert the exact HSLA tuple here (as tiny floating point differences
    // may arise depending on the HSL implementation); instead we round-trip
    // back to HEX and assert on the final color value.
    const overridden70 = tracks.solid[70];
    expect(overridden70).toBeDefined();
    if (overridden70) {
      expect(convertHslaToHex(overridden70)).toBe('#115EA3');
    }

    // O arquivo gerado deve conter o cabeçalho e os comentários de override.
    const fileContent = readFileSync(new URL('./color.generated.ts', import.meta.url), 'utf8');
    expect(fileContent).toContain(
      "// Generated by generateColorScaleWithLog('#0F6CBD', true, {"
    );
    expect(fileContent).toContain("//   70: '#115EA3',");
    expect(fileContent).toContain('// })');
    expect(fileContent).toContain('OVERRIDDEN: generated');
    expect(fileContent).toContain('#115EA3');
  });

  it('writes a header without overrides and includes canonical usage anchor comments', () => {
    const tracks = generateColorScaleWithLog('#0F6CBD', true);

    // Sanity check: extremes are still enforced when no overrides are provided
    expect(tracks.soft[0]).toEqual([0, 0, 100, 1]);
    expect(tracks.solid[100]).toEqual([0, 0, 0, 1]);

    const fileContent = readFileSync(new URL('./color.generated.ts', import.meta.url), 'utf8');

    // Header must reflect the exact parameters used, with an empty overrides object
    expect(fileContent).toContain(
      "// Generated by generateColorScaleWithLog('#0F6CBD', true, {})"
    );

    // Canonical usage anchor information should be present for the base color
    expect(fileContent).toContain('Original color darkness');
    expect(fileContent).toContain('usage anchor tone');

    // For #0F6CBD the darkness matches a canonical bucket exactly, so the
    // comment should use the "original color tone" wording instead of
    // "closest tone".
    expect(fileContent).toContain(
      'original color tone (#0F6CBD'
    );
    expect(fileContent).not.toContain('closest tone to original color (#0F6CBD');

    // Darkest tone should still be explicitly documented.
    expect(fileContent).toContain('100% darkness (black/darkest)');
  });

  it('uses "closest tone to original color" wording when darkness snaps to nearest bucket', () => {
    generateColorScaleWithLog('#135FA3', true);

    const fileContent = readFileSync(new URL('./color.generated.ts', import.meta.url), 'utf8');

    // For this color the original darkness sits between canonical buckets, so
    // the comment must indicate that the chosen tone is merely the closest
    // one, not an exact match.
    expect(fileContent).toContain('closest tone to original color (');
  });

  it('applies soft track overrides while still enforcing absolute extremes', () => {
    const overrides = {
      0: '#FF0000', // must be ignored (soft[0] stays white)
      20: '#FF0000', // valid soft-track override
      100: '#00FF00' // must be ignored (solid[100] stays black)
    } as const;

    const tracks = generateColorScaleWithLog('#0F6CBD', true, overrides);

    // Absolute extremes must remain neutral white/black
    expect(tracks.soft[0]).toEqual([0, 0, 100, 1]);
    expect(tracks.solid[100]).toEqual([0, 0, 0, 1]);

    // The soft-track override at tone 20 must be applied using the HSLA
    // conversion of #FF0000 → [0, 100, 50, 1].
    expect(tracks.soft[20]).toEqual([0, 100, 50, 1]);
  });

  it('documents anchor color and overrides in non-canonical mode when input is not too light', () => {
    const overrides = {
      50: '#123456',
      60: '#ABCDEF'
    } as const;

    const tracks = generateColorScaleWithLog('#0F6CBD', false, overrides);

    // Non-canonical mode must still enforce absolute extremes
    expect(tracks.soft[0]).toEqual([0, 0, 100, 1]);
    expect(tracks.solid[100]).toEqual([0, 0, 0, 1]);

    const fileContent = readFileSync(new URL('./color.generated.ts', import.meta.url), 'utf8');

    // Tone 50 should be documented as the anchor color and also mention that
    // it was overridden.
    expect(fileContent).toContain(
      'Anchor color (input) - OVERRIDDEN: generated'
    );
    expect(fileContent).toContain('#123456');

    // A non-anchor solid tone (e.g. 60) that is overridden in non-canonical
    // mode should still carry a generic OVERRIDDEN comment.
    expect(fileContent).toContain('#ABCDEF');
    expect(fileContent).toContain('OVERRIDDEN: generated');
  });

  it('documents anchor color without overrides in non-canonical mode when input is not too light', () => {
    const tracks = generateColorScaleWithLog('#0F6CBD', false);

    // Mesmo em modo não canônico, os extremos devem permanecer consistentes.
    expect(tracks.soft[0]).toEqual([0, 0, 100, 1]);
    expect(tracks.solid[100]).toEqual([0, 0, 0, 1]);

    const fileContent = readFileSync(new URL('./color.generated.ts', import.meta.url), 'utf8');

    // Como a cor de entrada não é clara demais e não há overrides, o tom 50
    // deve ser documentado como cor âncora de entrada, exercitando o ramo
    // "Anchor color (input) - ${hexColor.toUpperCase()}".
    expect(fileContent).toContain('Anchor color (input) - #0F6CBD');
  });

  it('re-centers tone 50 for very light inputs in non-canonical mode and documents it', () => {
    const tracks = generateColorScaleWithLog('#FFFFFF', false);

    // Even in non-canonical mode, very light inputs should not be used as the
    // solid-track anchor; tone 50 must be re-centered at L=50.
    expect(tracks.soft[0]).toEqual([0, 0, 100, 1]);
    expect(tracks.solid[100]).toEqual([0, 0, 0, 1]);
    expect(tracks.solid[50]?.[2]).toBe(50);

    const fileContent = readFileSync(new URL('./color.generated.ts', import.meta.url), 'utf8');

    // The log should explain that the mid tone was re-centered instead of
    // using the original, excessively light input color.
    expect(fileContent).toContain(
      'Re-centered mid tone (L=50) because input color (#FFFFFF'
    );
  });
});
