// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/generate-showcase-registry.cjs based on web-builder manifests.

export const cssPaths = {
  'fluent-2-microsoft': {
    core: '/build/fluent-2-microsoft/core.kiskadee.css',
    effects: '/build/fluent-2-microsoft/effects.kiskadee.css',
    palettes: {
      'ios|light': '/build/fluent-2-microsoft/ios.light.kiskadee.css',
    }
  },
  'ios-26-apple': {
    core: '/build/ios-26-apple/core.kiskadee.css',
    effects: '/build/ios-26-apple/effects.kiskadee.css',
    palettes: {
      'ios|light': '/build/ios-26-apple/ios.light.kiskadee.css',
    }
  },
  'ios-26-kiskadee': {
    core: '/build/ios-26-kiskadee/core.kiskadee.css',
    effects: '/build/ios-26-kiskadee/effects.kiskadee.css',
    palettes: {
      'ios|light': '/build/ios-26-kiskadee/ios.light.kiskadee.css',
      'ios|dark': '/build/ios-26-kiskadee/ios.dark.kiskadee.css',
    }
  },
  'material-design-3-google': {
    core: '/build/material-design-3-google/core.kiskadee.css',
    effects: '/build/material-design-3-google/effects.kiskadee.css',
    palettes: {
      'material|light': '/build/material-design-3-google/material.light.kiskadee.css',
    }
  },
} as const;

export type CssRegistry = typeof cssPaths;
