// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/generate-showcase-registry.cjs based on web-builder manifests.
import type { ComponentClassNameMap } from '@kiskadee/web-builder/types';

type ClassNamesModuleLike = { default: ComponentClassNameMap };

// Helper that wraps fetch and returns a "module-like" object compatible
// with the existing code in app/providers.tsx.
function loadJsonModule(path: string): Promise<ClassNamesModuleLike> {
  return fetch(path)
    .then((response) => {
      if (!response.ok) {
        throw new Error(`Failed to load classNamesMap JSON: ${path} (${response.status})`);
      }
      return response.json();
    })
    .then((json) => ({ default: json as ComponentClassNameMap }));
}

export const coreMaps = {
  'fluent-2-microsoft': () => loadJsonModule('/build/fluent-2-microsoft/core.kiskadee.json'),
  'ios-26-apple': () => loadJsonModule('/build/ios-26-apple/core.kiskadee.json'),
  'ios-26-kiskadee': () => loadJsonModule('/build/ios-26-kiskadee/core.kiskadee.json'),
  'material-design-3-google': () => loadJsonModule('/build/material-design-3-google/core.kiskadee.json'),
} as const;

export const paletteMaps = {
  'fluent-2-microsoft|default|light': () => loadJsonModule('/build/fluent-2-microsoft/default.light.kiskadee.json'),
  'ios-26-apple|default|light': () => loadJsonModule('/build/ios-26-apple/default.light.kiskadee.json'),
  'ios-26-kiskadee|default|light': () => loadJsonModule('/build/ios-26-kiskadee/default.light.kiskadee.json'),
  'ios-26-kiskadee|default|dark': () => loadJsonModule('/build/ios-26-kiskadee/default.dark.kiskadee.json'),
  'material-design-3-google|default|light': () => loadJsonModule('/build/material-design-3-google/default.light.kiskadee.json'),
} as const;

export const extraMaps = {
  'fluent-2-microsoft|default|light': () => fetch('/build/fluent-2-microsoft/extra.default.light.kiskadee.json').then((r) => r.json()),
  'ios-26-apple|default|light': () => fetch('/build/ios-26-apple/extra.default.light.kiskadee.json').then((r) => r.json()),
  'ios-26-kiskadee|default|light': () => fetch('/build/ios-26-kiskadee/extra.default.light.kiskadee.json').then((r) => r.json()),
  'ios-26-kiskadee|default|dark': () => fetch('/build/ios-26-kiskadee/extra.default.dark.kiskadee.json').then((r) => r.json()),
  'material-design-3-google|default|light': () => fetch('/build/material-design-3-google/extra.default.light.kiskadee.json').then((r) => r.json()),
} as const;

export const paletteIndex = {
  'fluent-2-microsoft': {
    segments: ['default'],
    themesBySegment: {
      "default": ['light']
    }
  },
  'ios-26-apple': {
    segments: ['default'],
    themesBySegment: {
      "default": ['light']
    }
  },
  'ios-26-kiskadee': {
    segments: ['default'],
    themesBySegment: {
      "default": ['light', 'dark']
    }
  },
  'material-design-3-google': {
    segments: ['default'],
    themesBySegment: {
      "default": ['light']
    }
  },
} as const;

export const designSystemMeta = {
  'fluent-2-microsoft': { displayName: "Default 2 by Microsoft" },
  'ios-26-apple': { displayName: "Default 26 by Apple" },
  'ios-26-kiskadee': { displayName: "Default 26 by Kiskadee" },
  'material-design-3-google': { displayName: "Material Design - Default (purple) 3 by Google" },
} as const;
