// Static registry for Kiskadee design system assets used by the showcase
//
// Important notes:
// - All artifacts generated by @kiskadee/web-builder (CSS + JSON)
//   are served from public/build/** of the @kiskadee/showcase project.
// - Because of that, this registry loads classNamesMap JSON files via fetch from
//   static URLs (for example: /build/ios-26-kiskadee/core.kiskadee.json)
//   instead of local dynamic imports.
// - To stay compatible with the current Providers implementation, each loader
//   returns an object shaped like an ESM module: { default: ComponentClassNameMap }.
//
// The public/build directory must be kept in sync with packages/web-builder/build
// by a sync script (at the monorepo root).

// NOTE: The concrete data for these registries is now auto-generated by
// scripts/generate-showcase-registry.cjs into
//   - design-systems.registry.generated.ts
//   - css.registry.generated.ts
//
// This file only re-exports the generated symbols to preserve the public API
// expected by the rest of the showcase app.

export * from './design-systems.registry.generated';
