// Static registry for Kiskadee template assets used by the showcase
//
// Important notes:
// - All artifacts generated by @kiskadee/web-builder (CSS + JSON)
//   are served from public/build/** of the @kiskadee/showcase project.
// - Because of that, this registry loads classNamesMap JSON files via fetch from
//   static URLs (for example: /build/ios-26-kiskadee/core.kiskadee.json)
//   instead of local dynamic imports.
// - To stay compatible with the current Providers implementation, each loader
//   returns an object shaped like an ESM module: { default: ComponentClassNameMap }.
//
// The public/build directory must be kept in sync with packages/web-builder/build
// by a sync script (at the monorepo root).

import type { ComponentClassNameMap } from '@kiskadee/web-builder/types';

type ClassNamesModuleLike = { default: ComponentClassNameMap };

// Helper that wraps fetch and returns a "module-like" object compatible
// with the existing code in app/providers.tsx.
function loadJsonModule(path: string): Promise<ClassNamesModuleLike> {
  return fetch(path)
    .then((response) => {
      if (!response.ok) {
        throw new Error(`Failed to load classNamesMap JSON: ${path} (${response.status})`);
      }
      return response.json();
    })
    .then((json) => ({ default: json as ComponentClassNameMap }));
}

export const coreMaps = {
  'ios-26-apple': () => loadJsonModule('/build/ios-26-apple/core.kiskadee.json'),
  'ios-26-kiskadee': () => loadJsonModule('/build/ios-26-kiskadee/core.kiskadee.json'),
  'material-design-3-google': () =>
    loadJsonModule('/build/material-design-3-google/core.kiskadee.json')
} as const;

export const paletteMaps = {
  // ios-26-apple palettes
  'ios-26-apple|ios|light': () => loadJsonModule('/build/ios-26-apple/ios.light.kiskadee.json'),
  // ios-26-kiskadee palettes
  'ios-26-kiskadee|ios|light': () =>
    loadJsonModule('/build/ios-26-kiskadee/ios.light.kiskadee.json'),
  'ios-26-kiskadee|ios|dark': () => loadJsonModule('/build/ios-26-kiskadee/ios.dark.kiskadee.json'),
  'ios-26-kiskadee|ios|darker': () =>
    loadJsonModule('/build/ios-26-kiskadee/ios.darker.kiskadee.json'),
  // material-design-3-google palettes
  'material-design-3-google|material|light': () =>
    loadJsonModule('/build/material-design-3-google/material.light.kiskadee.json')
} as const;

export const paletteIndex = {
  'ios-26-apple': {
    segments: ['ios'],
    themesBySegment: { ios: ['light'] }
  },
  'ios-26-kiskadee': {
    segments: ['ios'],
    themesBySegment: { ios: ['light', 'dark', 'darker'] }
  },
  'material-design-3-google': {
    segments: ['material'],
    themesBySegment: { material: ['light'] }
  }
} as const;

export const templateMeta = {
  'ios-26-apple': { displayName: 'iOS 26 — Apple' },
  'ios-26-kiskadee': { displayName: 'iOS 26 — Kiskadee' },
  'material-design-3-google': { displayName: 'Material Design 3 — Google' }
} as const;
