// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/generate-showcase-registry.cjs based on web-builder manifests.
import type { ComponentClassNameMap } from '@kiskadee/web-builder/types';

type ClassNamesModuleLike = { default: ComponentClassNameMap };

// Helper that wraps fetch and returns a "module-like" object compatible
// with the existing code in app/providers.tsx.
function loadJsonModule(path: string): Promise<ClassNamesModuleLike> {
  return fetch(path)
    .then((response) => {
      if (!response.ok) {
        throw new Error(`Failed to load classNamesMap JSON: ${path} (${response.status})`);
      }
      return response.json();
    })
    .then((json) => ({ default: json as ComponentClassNameMap }));
}

export const coreMaps = {
  'fluent-2-microsoft': () => loadJsonModule('/build/fluent-2-microsoft/core.kiskadee.json'),
  'ios-26-apple': () => loadJsonModule('/build/ios-26-apple/core.kiskadee.json'),
  'ios-26-kiskadee': () => loadJsonModule('/build/ios-26-kiskadee/core.kiskadee.json'),
  'material-design-3-google': () => loadJsonModule('/build/material-design-3-google/core.kiskadee.json'),
} as const;

export const paletteMaps = {
  'fluent-2-microsoft|ios|light': () => loadJsonModule('/build/fluent-2-microsoft/ios.light.kiskadee.json'),
  'ios-26-apple|ios|light': () => loadJsonModule('/build/ios-26-apple/ios.light.kiskadee.json'),
  'ios-26-kiskadee|ios|light': () => loadJsonModule('/build/ios-26-kiskadee/ios.light.kiskadee.json'),
  'ios-26-kiskadee|ios|dark': () => loadJsonModule('/build/ios-26-kiskadee/ios.dark.kiskadee.json'),
  'material-design-3-google|material|light': () => loadJsonModule('/build/material-design-3-google/material.light.kiskadee.json'),
} as const;

export const paletteIndex = {
  'fluent-2-microsoft': {
    segments: ['ios'],
    themesBySegment: {
      "ios": ['light']
    }
  },
  'ios-26-apple': {
    segments: ['ios'],
    themesBySegment: {
      "ios": ['light']
    }
  },
  'ios-26-kiskadee': {
    segments: ['ios'],
    themesBySegment: {
      "ios": ['light', 'dark']
    }
  },
  'material-design-3-google': {
    segments: ['material'],
    themesBySegment: {
      "material": ['light']
    }
  },
} as const;

export const templateMeta = {
  'fluent-2-microsoft': { displayName: "iOS 2 by Microsoft" },
  'ios-26-apple': { displayName: "iOS 26 by Apple" },
  'ios-26-kiskadee': { displayName: "iOS 26 by Kiskadee" },
  'material-design-3-google': { displayName: "Material Design - Purple 3 by Google" },
} as const;
